[package]
name = "region_labeling"
version = "0.1.0"
authors = ["gonzalotittarelli <gonzalotittarelli@hotmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3