[package]
name = "region_labeling_concurrent"
version = "0.1.0"
authors = ["gonzalotittarelli <gonzalotittarelli@hotmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
crossbeam-channel = "0.3"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3